-- MySQL Script generated by MySQL Workbench
-- Thu Sep 23 16:38:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema car_sales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_sales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_sales` DEFAULT CHARACTER SET utf8 ;
USE `car_sales` ;

-- -----------------------------------------------------
-- Table `car_sales`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_sales`.`person` (
  `id_person` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NULL,
  `date_of_birth` DATE NULL,
  PRIMARY KEY (`id_person`),
  UNIQUE INDEX `id_person_UNIQUE` (`id_person` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_sales`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_sales`.`manufacturer` (
  `id_manufacturer` INT NOT NULL AUTO_INCREMENT,
  `name_manufacturer` VARCHAR(45) NULL,
  PRIMARY KEY (`id_manufacturer`),
  UNIQUE INDEX `id_manufacturer_UNIQUE` (`id_manufacturer` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_sales`.`car_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_sales`.`car_model` (
  `id_model` INT NOT NULL AUTO_INCREMENT,
  `model_description` VARCHAR(45) NULL,
  `id_manufacturer` INT NOT NULL,
  PRIMARY KEY (`id_model`),
  UNIQUE INDEX `id_model_UNIQUE` (`id_model` ASC) VISIBLE,
  INDEX `fk_car_model_manufacturer_idx` (`id_manufacturer` ASC) VISIBLE,
  CONSTRAINT `fk_car_model_manufacturer`
    FOREIGN KEY (`id_manufacturer`)
    REFERENCES `car_sales`.`manufacturer` (`id_manufacturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_sales`.`car_sell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_sales`.`car_sell` (
  `id_purchase` INT NOT NULL,
  `date_purchase` DATE NULL,
  `price_purchase` DECIMAL(10,2) NULL,
  `person_id_person` INT NOT NULL,
  `id_model` INT NOT NULL,
  PRIMARY KEY (`id_purchase`),
  UNIQUE INDEX `id_sell_UNIQUE` (`id_purchase` ASC) VISIBLE,
  INDEX `fk_car_sell_person1_idx` (`person_id_person` ASC) VISIBLE,
  INDEX `fk_car_sell_car_model1_idx` (`id_model` ASC) VISIBLE,
  CONSTRAINT `fk_car_sell_person1`
    FOREIGN KEY (`person_id_person`)
    REFERENCES `car_sales`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_sell_car_model1`
    FOREIGN KEY (`id_model`)
    REFERENCES `car_sales`.`car_model` (`id_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
